//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediatekaEntities3 : DbContext
    {
        public MediatekaEntities3()
            : base("name=MediatekaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Автори> Автори { get; set; }
        public virtual DbSet<Виконавці> Виконавці { get; set; }
        public virtual DbSet<Композиції> Композиції { get; set; }
        public virtual DbSet<Країни> Країни { get; set; }
        public virtual DbSet<Музичні_жанри> Музичні_жанри { get; set; }
    }
}
