//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виконавці
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Виконавці()
        {
            this.Композиції = new HashSet<Композиції>();
        }
    
        public int id { get; set; }
        public string Виконавець { get; set; }
        public Nullable<System.DateTime> Дата_народження { get; set; }
        public Nullable<int> id_Країна { get; set; }
        public int id_музичний_жанр { get; set; }
    
        public virtual Країни Країни { get; set; }
        public virtual Музичні_жанри Музичні_жанри { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Композиції> Композиції { get; set; }
    }
}
