//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Композиції
    {
        public int id { get; set; }
        public int id_Виконавець { get; set; }
        public string Композиція { get; set; }
        public int id_Автор { get; set; }
        public System.TimeSpan Тривалість { get; set; }
        public string Слова { get; set; }
        public float Обсяг_файлу_мб_ { get; set; }
        public System.DateTime Дата_створення { get; set; }
    
        public virtual Автори Автори { get; set; }
        public virtual Виконавці Виконавці { get; set; }
    }
}
